# Generated by Django 5.0.6 on 2024-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_remove_choice_votes_vote_voter_vote_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
