# Generated by Django 5.0.6 on 2024-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0003_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
